#############################################################################
# Makefile for building: Aeciumo
# Generated by qmake (2.01a) (Qt 4.8.4) on: ?? 6? 26 18:34:06 2014
# Project:  Aeciumo.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Aeciumo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = aeciumo.cpp \
		connectInternet.cpp \
		main.cpp moc_aeciumo.cpp \
		moc_connectInternet.cpp \
		qrc_aeciumo.cpp
OBJECTS       = aeciumo.o \
		connectInternet.o \
		main.o \
		moc_aeciumo.o \
		moc_connectInternet.o \
		qrc_aeciumo.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Aeciumo.pro
QMAKE_TARGET  = Aeciumo
DESTDIR       = 
TARGET        = Aeciumo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Aeciumo.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Aeciumo.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Aeciumo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Aeciumo1.0.0 || $(MKDIR) .tmp/Aeciumo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Aeciumo1.0.0/ && $(COPY_FILE) --parents aeciumo.h connectInternet.h networkState.h qssReader.h .tmp/Aeciumo1.0.0/ && $(COPY_FILE) --parents aeciumo.qrc .tmp/Aeciumo1.0.0/ && $(COPY_FILE) --parents aeciumo.cpp connectInternet.cpp main.cpp .tmp/Aeciumo1.0.0/ && (cd `dirname .tmp/Aeciumo1.0.0` && $(TAR) Aeciumo1.0.0.tar Aeciumo1.0.0 && $(COMPRESS) Aeciumo1.0.0.tar) && $(MOVE) `dirname .tmp/Aeciumo1.0.0`/Aeciumo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Aeciumo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_aeciumo.cpp moc_connectInternet.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aeciumo.cpp moc_connectInternet.cpp
moc_aeciumo.cpp: qssReader.h \
		connectInternet.h \
		networkState.h \
		aeciumo.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) aeciumo.h -o moc_aeciumo.cpp

moc_connectInternet.cpp: networkState.h \
		connectInternet.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) connectInternet.h -o moc_connectInternet.cpp

compiler_rcc_make_all: qrc_aeciumo.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_aeciumo.cpp
qrc_aeciumo.cpp: aeciumo.qrc \
		Lib/baslib \
		Lib/.baslib \
		Resources/btn_set_normal.png \
		Resources/btn_set_press.png \
		Resources/btn_black_normal.png \
		Resources/btn_black_press.png \
		Resources/butterfly.png \
		Resources/btn_black_hover.png \
		Resources/btn_close_highlight.png \
		Resources/down_Arrow_Off.png \
		Resources/btn_close_disable.png \
		Resources/combo_login.png \
		Resources/btn_mini_down.png \
		Resources/btn_mini_normal.png \
		Resources/logo.png \
		Resources/background.png \
		Resources/btn_close_down.png \
		Resources/btn_set_hover.png \
		Resources/btn_mini_highlight.png \
		Resources/checkbox_unchecked_hover.png \
		Resources/checkbox_checked_hover.png \
		Resources/checkbox_checked.png \
		Resources/checkbox_unchecked.png \
		Resources/down_Arrow_On.png \
		Qss/styleSheet_button_minimum.qss \
		Qss/styleSheet_checkBox.qss \
		Qss/styleSheet_button_close.qss \
		Qss/styleSheet_button_settings.qss \
		Qss/styleSheet_lineEdit_password.qss \
		Qss/styleSheet_comboBox_id.qss \
		Qss/styleSheet_label_title.qss \
		Qss/styleSheet_black_button.qss
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name aeciumo aeciumo.qrc -o qrc_aeciumo.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

aeciumo.o: aeciumo.cpp aeciumo.h \
		qssReader.h \
		connectInternet.h \
		networkState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aeciumo.o aeciumo.cpp

connectInternet.o: connectInternet.cpp connectInternet.h \
		networkState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectInternet.o connectInternet.cpp

main.o: main.cpp aeciumo.h \
		qssReader.h \
		connectInternet.h \
		networkState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_aeciumo.o: moc_aeciumo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aeciumo.o moc_aeciumo.cpp

moc_connectInternet.o: moc_connectInternet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectInternet.o moc_connectInternet.cpp

qrc_aeciumo.o: qrc_aeciumo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_aeciumo.o qrc_aeciumo.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

